x/zktx/keeper/msg_server.go, x/zktx/keeper/msg_server_ecdsa_test.go, x/zktx/keeper/msg_server_test.go
This splits off the ECDSA example since we'll need to adapt that later"
=> Rename gnark groth16 curve, make it actually do something, add better tests

src/bus.rs, src/bus/command_response.rs, src/consensus.rs, src/mempool.rs, src/node_state.rs, src/p2p/network.rs, src/rest/endpoints.rs, src/tools/mock_workflow.rs, src/validator_registry.rs
This generates documentation for bus messages like so:
=> Implement BusMessage to document bus messages

src/utils/static_type_map.rs
=> 🍻 Fix a real problem

src/p2p/stream.rs
Because the futures are cancellable, there was an opportunity to end up partially reading a stream.
=> Atomicize read/writes from/to the TCP stream

src/consensus.rs, src/consensus/metrics.rs, src/history.rs, src/mempool.rs, src/mempool/metrics.rs, src/node_state.rs, src/rest.rs, src/tools/mock_workflow.rs, src/utils/conf.rs
Done
- mempool
- consensus
- node state
- history
- rest api
- p2p
=> Init bus clients during build phase

.github/workflows/ci.yml
Cache dependencies to fasten CI
=> 👷 CI cache cargo build

.github/workflows/ci.yml, src/mempool.rs, src/mempool/storage.rs, tests/e2e_test.rs
646aead is the last working commit for the e2e test
The commit just after that 91f1841 breaks the test.
The commit just after 91f1841 which is 21f9c49
is good after applying this patch.
=> fix a part of main by half reverting a change on mempool

src/consensus.rs, src/consensus/utils.rs, src/data_availability.rs, src/indexer.rs, src/mempool.rs, src/mempool/metrics.rs, src/mempool/storage.rs, tests/e2e_test.rs
keep track of previous sent sync requests
in order to avoid resending one.
=> remove Block from consensus

src/mempool.rs, src/mempool/storage.rs
order the tips based on the list of validators
given by the consensus.
=> keep the order of validators in a Cut

src/consensus.rs, src/consensus/module.rs, src/consensus/utils.rs, src/data_availability.rs, src/model.rs, src/utils/conf.rs, src/utils/conf_defaults.ron, tests/e2e_test.rs, tests/test_helpers.rs
C’est un peu moche parce que je garde tout le state et j’utilise l’enum de manière weak, mais c’est une galère sans nom d’essayer de faire autrement à cause de la syntaxe en if let partout
=> Reintroduce consensus joining logic, rework genesis handling, split bft_round_state

src/bin/indexer.rs, src/bin/node.rs, src/consensus.rs, src/rest.rs, src/rest/client.rs, src/rest/endpoints.rs, tests/consensus_tests.rs, tests/fixtures/ctx.rs
=> 🧪 Add e2e test on rejoin

src/consensus.rs, src/mempool/storage.rs
=> strictly incleasing cuts

src/consensus.rs, src/indexer.rs, src/indexer/api.rs, src/indexer/model.rs
Fixes https://github.com/Hyle-org/hyle/issues/288
=> fix: improve indexer tests & fix sql command typing

Cargo.lock, Cargo.toml, src/p2p.rs, src/p2p/fifo_filter.rs, src/p2p/peer.rs
Remove bloomfiter as it can have false positives
Use a new Fifo filter, constant size, no false positives possibles,
false negatives possible if size is small, but not a problem in our case
=> 🐛 Fix message not broadcasted

src/consensus.rs, src/consensus/role_follower.rs, src/consensus/role_leader.rs
Creates 2 files role_leader/role_follower and put specific handlers in them out of consensus.rs
=> Split consensus between Follower and Leader

.github/workflows/docker.yml
| Event               | Ref                           | Docker Tags                |
|---------------------|-------------------------------|----------------------------|
| `pull_request`      | `refs/pull/2/merge`           | `pr-2`                     |
| `push`              | `refs/heads/master`           | `master`                   |
| `push`              | `refs/heads/releases/v1`      | `releases-v1`              |
| `push tag`          | `refs/tags/v1.2.3`            | `v1.2.3`, `latest`         |
| `push tag`          | `refs/tags/v2.0.8-beta.67`    | `v2.0.8-beta.67`, `latest` |
| `workflow_dispatch` | `refs/heads/master`           | `master`                   |
Closes #348
=> 👷 Build & Push docker images to GCR

tests/build_proofs.sh
=> 🔨 Fix build_proofs.sh script

src/node_state.rs
Closes [#362](https://github.com/Hyle-org/hyle/issues/362)
=> feat: one blobTx can change same contract state multiple times

.github/codecov.yml, Cargo.lock, Cargo.toml, crates/bonsai-runner/Cargo.toml, crates/bonsai-runner/src/lib.rs
=> ✨ Add helper crate to prove on bonsai

Cargo.lock, Cargo.toml, src/indexer.rs, src/indexer/api.rs, src/indexer/migrations/20241009154948_create_tables.sql, src/indexer/model.rs, tests/fixtures/ctx.rs, tests/fixtures/test_data.sql, tests/tx_settlement_test.rs
See tests for format
This allows knowing if some blobs remain unproven / incorrectly proven.
=> Return proofs as part of blob_transaction calls

src/data_availability.rs, src/data_availability/blocks.rs, src/utils/db.rs
=> 🐛 Fix DA issues

src/indexer.rs, src/mempool.rs, src/mempool/storage.rs, src/model.rs, src/node_state.rs, src/node_state/verifiers.rs
Closes [#423](https://github.com/Hyle-org/hyle/issues/423)
=> ✨ Only remove proofs for DP of other validators

tools/set-logs.sh
used with an alias
```bash
alias e='source [...]/set-logs.sh add'
```
=> 🔨 Tool to set RUST_LOG env var

.github/workflows/ci.yml
Pour accélérer l'execution des smart contract au genesis et dans les
tests
=> 👷 Use r0vm executor in CI

src/consensus.rs, src/consensus/role_follower.rs
- **don't refuse late proposal**
- **remove too_late test**
=> ✅ Fix tests: don't refuse late proposal

src/bin/node.rs, src/consensus.rs, src/consensus/utils.rs, src/data_availability.rs, src/data_availability/blocks_memory.rs, src/data_availability/blocks_sled.rs, src/data_availability/codec.rs, src/data_availability/node_state.rs, src/genesis.rs, src/indexer.rs, src/indexer/api.rs, src/indexer/migrations/20241009154948_create_tables.sql, src/mempool.rs, src/mempool/storage.rs, src/model.rs, src/model/consensus.rs, src/model/indexer.rs, src/single_node_consensus.rs, src/tools/rest_api_client.rs, tests/fixtures/ctx.rs, tests/indexer_tests.rs, tools/test_log_viewer.html
Also:
- Fix an issue with the blob_proof_output primary key (incorrect)
- Use the Genesis module for both single and regular consensus modules
=> 🐛  Use the consensus proposal hash as the block hash, propagate to the indexer

src/bin/hyled.rs, src/tools/contract_runner.rs, src/tools/mock_workflow.rs, src/tools/rest_api_client.rs, tests/fixtures/ctx.rs, tests/fixtures/test_helpers.rs
- **♻️  Split ApiHttpClient for node & indexer**
- **♻️  Split ApiHttpClient for node & indexer**
=> ♻️ Split ApiHttpClient for node & indexer

crates/client-sdk/src/helpers.rs, crates/client-sdk/src/lib.rs, crates/client-sdk/src/transaction_builder.rs
used in simple token example https://github.com/Hyle-org/examples/blob/0e5915cb465d9eb4b9cc65ae871e8d5a1edfc4e4/simple-token/host/src/main.rs#L158
=> 🔨 Add prove helper function to client sdk

.github/docker/Dockerfile.alpine, .github/workflows/custom-docker.yml, Dockerfile
Once merged, will be available at `ghcr.io/hyle-org/alpine:main` and can be used by:
- #529
=> ✨ Add new custom alpine image

Cargo.lock, Cargo.toml, src/consensus.rs, src/genesis.rs, src/indexer/contract_state_indexer.rs, src/mempool.rs, src/single_node_consensus.rs, src/utils/modules.rs, tests/consensus_tests.rs, tests/fixtures/ctx.rs, tests/fixtures/test_helpers.rs
=> 🐛 Always try to rejoin consensus when restarting the node

src/data_availability/node_state.rs, src/indexer.rs, src/indexer/api.rs, src/indexer/contract_state_indexer.rs, src/indexer/migrations/20241009154948_create_tables.sql, src/mempool.rs, src/model.rs, src/model/indexer.rs, tests/fixtures/test_data.sql
=> Store TXs in order in blocks and return that order

src/data_availability/node_state.rs, src/data_availability/node_state/ordered_tx_map.rs, src/data_availability/node_state/timeouts.rs, src/model.rs, src/model/data_availability.rs
We still don't settle TXs after the timeout (see `should_panic` test), will fix that in a later PR
=> ✨  Prevent already settled TXs from timing out, refactor + tests

src/consensus/utils.rs, src/mempool.rs, src/model.rs
Fix https://github.com/Hyle-org/hyle/issues/561
=> ⚡️ Remove write! from hash functions

src/utils/modules.rs
- Proofs can't be deserialized, to fix
=> ⚡️ use buffer writer instead of file io directly

Dockerfile, Dockerfile.dependencies
=> 💚 Fix Dockerfile after move to crates

src/consensus.rs, src/consensus/role_follower.rs, src/consensus/role_leader.rs, src/consensus/role_timeout.rs, src/consensus/utils.rs, src/data_availability.rs, src/data_availability/blocks_fjall.rs, src/data_availability/blocks_memory.rs, src/genesis.rs, src/indexer.rs, src/mempool.rs, src/mempool/api.rs, src/model.rs, src/node_state.rs, src/node_state/module.rs, src/p2p.rs, src/p2p/peer.rs, src/rest.rs, src/single_node_consensus.rs, src/utils/logger.rs, src/utils/modules.rs
=> 🔊  Reduce spam of logs

.github/workflows/github_stars.yml
- **💚 Fix github stars ci**
- **better cache**
- **Run only once at 10am**
=> 💚 Fix github stars ci

src/consensus.rs, src/data_availability.rs, src/mempool.rs, src/mempool/storage.rs, src/single_node_consensus.rs
Fix https://github.com/Hyle-org/hyle/issues/641
=> ✨ Send PoDAUpdate when receiving enough signatures

Cargo.lock, Cargo.toml
=> 🔖 Bump version to 0.7.2

Cargo.lock, Cargo.toml, crates/bonsai-runner/Cargo.toml
Version 0.8.2 has been yanked from crates.io
Closes #669
=> ⬇️  Downgrade to axum 0.8.1 after yanked version

crates/client-sdk/src/helpers.rs, crates/client-sdk/src/transaction_builder.rs, src/genesis.rs, src/indexer/contract_state_indexer.rs, src/indexer/migrations/20241009154948_create_tables.sql, src/mempool/test/async_data_proposals.rs, src/node_state/ordered_tx_map.rs
Le transaction_builder est pas adapté car on ne peut pas les prouver ni vraiment les executer.
=> ✨ Helper function to register Hyle contracts using ProvableBlobTx

crates/client-sdk/src/helpers.rs, crates/hyle-loadtest/src/lib.rs, crates/hyle-loadtest/src/main.rs
=> 🐛 fix loadtest

Cargo.lock, Cargo.toml, crates/client-sdk/src/transaction_builder.rs, crates/contracts/hydentity/Cargo.toml, crates/contracts/hydentity/examples/host.rs, crates/contracts/risc0-recursion/tests/recursion.rs, crates/hyle-loadtest/src/lib.rs, crates/hyle-model/Cargo.toml, tests/amm_test.rs, tests/fixtures/ctx.rs, tests/fixtures/test_helpers.rs, tests/hyllar_test.rs, tests/uuid_test.rs
To replace ☠️  hyrun and have a clean cli to send transactions (sometimes
usefull)
=> ✨ Add Hydentity host example + ♻️  Refacto builder

src/bin/indexer.rs, src/indexer/da_listener.rs, src/node_state.rs
=> 🩹 DA Listener restart stream for saved last block

Cargo.toml
=> 🔧 Add contract-sdk to workspace

crates/client-sdk/src/rest_client.rs, crates/hyle-model/src/api.rs
=> 🐛 Fix indexer client get blobs endpoint

GRANTS.md
removed trust infrastructure link
=> 📝 Update grants.md

src/data_availability.rs, src/indexer.rs, src/mempool/block_construction.rs, src/mempool/storage_fjall.rs, src/p2p/peer.rs, src/utils/logger.rs, src/utils/modules.rs
=> ✨ Improved Loggers

crates/client-sdk/src/tcp.rs, crates/contracts/staking/src/state.rs, src/consensus.rs, src/mempool.rs, src/mempool/own_lane.rs, tests/fixtures/ctx.rs, tests/lanes_test.rs, tools/test_log_viewer.html
- Fix issue in mempool where we wouldn't disseminate (as we're still signing)
- Fix processing of staking without Consensus in mempool
- Move processing of staking actions to Stake
- Fix TCP server peer IP to account for ports
- Fix ordering issue in log viewer
=> ✨ Make LaneManager mode work correctly

Cargo.lock, src/consensus.rs, src/consensus/role_follower.rs, src/consensus/role_leader.rs, src/consensus/role_timeout.rs, src/tests/autobahn_testing.rs
The added autobahn tests show that things aren't really working as hoped.
=> ✅ Re-propose prepare on view change in some cases, add test

Cargo.toml, crates/contracts/Cargo.toml, crates/contracts/build.rs, crates/contracts/metadata.rs
e.g.
```sh
cargo build -p hyle-contracts -F build -vv -F amm
```
=> ✨ Add option to build a specific contract

.cargo/config.toml, crates/hyle-net/src/tcp.rs, src/consensus.rs, src/indexer.rs, src/p2p.rs, src/p2p/peer.rs, src/utils/modules.rs
=> ➖ Remove tokio_unstable flag

crates/hyle-verifiers/src/lib.rs
Add environment variable control for noir verifier temporary files. When HYLE_KEEP_NOIR_TMP_FILES is set to "true", temporary files used during noir proof verification are preserved for debugging purposes, otherwise they're automatically cleaned up.
Closes #1002
=> 🐛 fix clean or preserve noir temp files based on env var

.github/workflows/turmoil-p2p-tests.yml, crates/hyle-net/tests/basic.rs
Add a job triggered for hyle-net PRs
=> :test_tube: Make p2p turmoil test fail if handshake does not end.

crates/hyle-net/src/tcp/p2p_server.rs, crates/hyle-net/src/tcp/tcp_server.rs
This reverts commit decaa9a2f624cd6b4a2a01a605a233f75c807a10.
=> :back: Revert "✨ Prevent sending message based on ping (#1076)"

src/modules/websocket.rs
Let websocket register a "topic" and get the messages related to it
=> ✨ Websocket: Add topic messages

src/mempool.rs, src/mempool/own_lane.rs
This does what it always was meant to do
=> 🐛 Fix creation of DP, only disseminate if relevant

crates/hyle-net/src/tcp.rs, crates/hyle-net/src/tcp/p2p_server.rs, crates/hyle-net/src/tcp/tcp_client.rs, crates/hyle-net/src/tcp/tcp_server.rs, crates/hyle-net/tests/basic.rs
=> :zap: TCP - Retrigger handshakes on failures, better logs,

src/bus.rs, src/bus/command_response.rs, src/consensus.rs, src/data_availability.rs, src/genesis.rs, src/indexer/contract_state_indexer.rs, src/mempool.rs, src/mempool/api.rs, src/modules/prover.rs, src/modules/websocket.rs, src/node_state/module.rs, src/p2p.rs, src/p2p/network.rs, src/tcp_server.rs, src/tools/mock_workflow.rs, src/utils/modules.rs
Prep work for future split of modules
=> ♻️ Remove trait BusMessage

crates/hyle-crypto/src/lib.rs, crates/hyle-model/src/block.rs, crates/hyle-model/src/node/consensus.rs, crates/hyle-modules/src/node_state.rs, src/consensus.rs, src/consensus/role_follower.rs, src/consensus/role_leader.rs, src/consensus/role_timeout.rs, src/genesis.rs, src/mempool.rs, src/p2p.rs, src/p2p/network.rs, src/single_node_consensus.rs, src/tests/autobahn_testing.rs
This allows stronger typing of votes & quorum certificates.
=> 🐛 Switch consensus to MsgWithHeader

.github/docker/Dockerfile.alpine
=> ⏪️ Revert "⬆️ Upgrade bb version"

src/mempool/block_construction.rs
=> :bug: Fix reverse dp order when creating a block

GRANTS.md
=> 👷 Update GRANTS.md

src/indexer.rs
Postgres is not ok with bulk insert + on conflict do update
=> :bug: Avoid duplicate tx make crash indexer

crates/hyle-modules/src/bus/command_response.rs, crates/hyle-modules/src/modules/admin.rs, crates/hyle-modules/src/modules/bus_ws_connector.rs, crates/hyle-modules/src/modules/contract_state_indexer.rs, crates/hyle-modules/src/modules/da_listener.rs, crates/hyle-modules/src/modules/mod.rs, crates/hyle-modules/src/modules/prover.rs, crates/hyle-modules/src/modules/rest.rs, crates/hyle-modules/src/modules/websocket.rs, crates/hyle-modules/src/node_state/module.rs, crates/hyli-tools/src/bin/block_dbg.rs, crates/hyli-tools/src/gcs_block_uploader.rs, crates/hyli-tools/src/signed_da_listener.rs, src/consensus.rs, src/consensus/module.rs, src/data_availability.rs, src/data_availability/module.rs, src/entrypoint.rs, src/genesis.rs, src/indexer.rs, src/mempool.rs, src/mempool/module.rs, src/p2p.rs, src/rest.rs, src/single_node_consensus.rs, src/tcp_server.rs, src/utils/conf.rs, src/utils/conf_defaults.toml, src/utils/integration_test.rs, tests/fixtures/test_helpers.rs
Missing http server to trigger the event
=> 💥  :floppy_disk:  Admin module - persist modules on event v1

crates/hyle-modules/src/node_state.rs, crates/hyle-modules/src/node_state/test/node_state_tests.rs
Fix made in #1382 for block after 445 000, now from genesis
=> 🐛 Enable timeout fix from genesis

crates/hyle-model/src/transaction.rs
Fixes https://github.com/hyli-org/hyli/issues/1342
=> 🐛 Make VerifiedProofTx hash match ProofTx hash

src/consensus/role_follower.rs
=> 🐛 Fix dissemination fees checks

Cargo.lock, crates/hylix/Cargo.toml, crates/hylix/README.md, crates/hylix/src/commands/devnet.rs, crates/hylix/src/main.rs
- **move to up & down**
- **Update readme**
- **Bump to 0.2.0**
=> ♻️ Hylix up & down

crates/client-sdk/src/helpers.rs, crates/client-sdk/src/lib.rs, crates/client-sdk/src/tests.rs, crates/client-sdk/src/transaction_builder.rs, crates/contracts/amm/src/client/tx_executor_handler.rs, crates/contracts/hydentity/src/client/tx_executor_handler.rs, crates/contracts/hyllar/src/client/tx_executor_handler.rs, crates/contracts/smt-token/Cargo.toml, crates/contracts/smt-token/src/client/tx_executor_handler.rs, crates/contracts/smt-token/tests/smt_integ_tests.rs, crates/contracts/staking/src/client/tx_executor_handler.rs, crates/contracts/uuid-tld/src/client/tx_executor_handler.rs, crates/hyli-modules/src/modules/contract_state_indexer.rs, crates/hyli-modules/src/modules/prover/prover_tests.rs, crates/hyli-modules/src/utils/native_verifier_handler.rs
=> ✅ Start testing client sdk

crates/client-sdk/Cargo.toml, crates/client-sdk/src/rest_client.rs, crates/hyli-model/src/api.rs, crates/hyli-modules/src/modules/rest.rs, crates/hyli-net/Cargo.toml, crates/hyli-net/src/http.rs
can be used to be exported to (e.g.) jaeger
=> 🔍️ Add some instrumentation
