hyli-org/hyli

x/zktx/keeper/gnark/gnark.go, x/zktx/keeper/msg_server_ecdsa_test.go, x/zktx/keeper/msg_server_test.go
Rationale: this allows using the Len properly and prevents a headache for the user
=> Use fixed-size arrays for sender/caller/TX

x/zktx/keeper/gnark/gnark.go, x/zktx/keeper/msg_server.go, x/zktx/keeper/msg_server_ecdsa_test.go, x/zktx/keeper/msg_server_groth16_test.go
- add PayloadHash and Success to HyleCircuit
- compute the payload hash in both groth16 and ecdsa tests.
=> keeper test fixing

master.ron, slave.ron, src/bin/client.rs, src/bin/node.rs, src/consensus.rs, src/mempool.rs, src/p2p.rs, src/p2p/network.rs, src/p2p/peer.rs, src/utils/conf.rs
- 2 way communication between Peer <> Consensus & Peer <> Mempool :
`Mempool ----- MempoolNetMessage(msg) ----->  Peer --> MempoolCommand::HandleNetMessage(msg) ----> Mempool`
`Consensus --- ConsensusNetMessage(msg) --->  Peer --> ConsensusCommand::HandleNetMessage(msg) --> Consensus`
- Add a ping-pong between peers because I had it on a branch and I took some work I did there to start this work bu I can remove this ping pong if it's confusing !
=> ✨ Relay messages from & to network

.cargo/config.toml, Cargo.lock, Cargo.toml, src/bin/node.rs
Adds tokio-console integration for async runtime observability: https://github.com/tokio-rs/console
**NOTABLE CHANGE**: this includes RUST_LOG behaviour, which I set to "info" by default.
Unfortunately requires a build flag for tokio, so added a .cargo/config.toml
Also give explicit names to the task using the experimental API.
=> Add tokio-console integration + RUST_LOG logging conf

.github/workflows/ci.yml
following https://stackoverflow.com/questions/71180135/github-actions-how-can-i-cache-the-docker-images-for-testcontainers blindly
=> fix: cache docker images when running CI

src/mempool.rs, src/mempool/metrics.rs, src/mempool/storage.rs
- renamed CarProposal -> DataProposal
- renamed Vote -> DataVote
- removed CarId
- Cars refers to their parent via a hash
- removed Poa from Car, a Car now contains a parent_hash and the txs
- add Poa in Lane
- DataProposal contains a Car and a parent Poa
- Storage now has the current DataProposal which will become a Car later
- which means Lanes now contain only Cars
=> mempool refactoring based on communal code review

src/consensus.rs, src/consensus/utils.rs, src/utils/crypto.rs, tools/docker-compose.yml
Introduction des view changes dans le consensus
Principe:
- Le but d'un timeout/view change est de changer de leader si celui choisi est byzantin (s'il ne va pas bout et ne propose pas de commit).  L'idée est donc de garder la même consensus proposal (slot s), tout en incrémentant la view pour passer au leader suivant dans la liste.
- Le leader ne prend pas part au timeout round (son but est de commit, il devrait retry ses messages pour arriver à commit mais en aucun cas déclencher un timeout). On peut voir le workflow de timeout comme une protection des followers contre le leader s'il ne fait pas correctement son boulot.
- Dès que le next leader reçoit un timeout certificate du réseau, qui atteste que c'est bien à lui de prendre la main, il l'utilise comme ticket pour émettre un Prepare …
=> Implement view changes

src/model.rs, src/node_state.rs, src/node_state/ordered_tx_map.rs
Objectifs:
- du code plus simple à lire
- plus performant
Je pense que je strike un bon middle ground, mais malheureusement faire des sous-fonctions va être relou à cause des borrow de `Self`, sauf à faire encore plus de méthodes qui borrow pas self.
Closes [#394](https://github.com/Hyle-org/hyle/issues/394)
=> ♻️ Refactor node_state settlement logic

src/autobahn_testing.rs, src/bin/indexer.rs, src/bin/node.rs, src/bus.rs, src/bus/command_response.rs, src/consensus.rs, src/consensus/api.rs, src/data_availability.rs, src/data_availability/api.rs, src/genesis.rs, src/indexer.rs, src/mempool.rs, src/mempool/api.rs, src/mempool/storage.rs, src/model.rs, src/p2p.rs, src/p2p/peer.rs, src/rest.rs, src/single_node_consensus.rs, src/tools/mock_workflow.rs, src/utils/db.rs, src/utils/modules.rs, src/utils/static_type_map.rs
- adapt handle_messages a bit (remove nested generated blocks)
- store receivers in variables before select loop
- clean receivers (consume remaining messages) after loop breaks
- order start/stop : start A, B, C, close C, B, A
- persist mempool/consensus on shutdown
Notes
On pimp la macro bus_client en rajoutant des while loops après la select loop, pour vider les topics écoutés dans la select loop (un event shutdown fait break la loop sans garantie d'avoir tout consommé).
Persister le state n'est pertinent que pour redémarrer sans perdre des txs à traiter. Donc dans Mempool, toutes les txs non encore commit doivent être persistées pour ne pas être perdues, et traiter au prochain démarrage de la node.
Il faut ordonner le démarrage des modules, pour ouvrir les apis en dernier, et les …
=> :sparkles:  Graceful shutdown

src/consensus.rs, src/consensus/role_leader.rs, src/consensus/role_timeout.rs, src/consensus/utils.rs, src/data_availability.rs, src/genesis.rs, src/model.rs, src/model/consensus.rs
Don't use the consensusProposalHash when timing out, don't pass next_leader as it's unnecessary
=> 🐛 Hash all critical fields in ConsensusProposal, refactor

Cargo.toml
This allows doing `cargo run --bin hyle-loadtest` from the root
=> 👷‍♂️ Default workspace members

.github/workflows/release.yml
as it's broken & needs to be done *before* tagging the version
=> 💚 Fix release workflow by removing bump version

crates/hyle-model/src/node/mempool.rs, src/mempool.rs
- we don't need to clear the data-proposal cache when removing proofs
- the context ended up serialising full blobs slowly, this is un-necessary.
=> ⚡  Remove two simple slowdown cases

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/bonsai-runner/Cargo.toml, crates/client-sdk/Cargo.toml, crates/contract-sdk/Cargo.toml, crates/contracts/Cargo.toml, crates/contracts/amm/Cargo.toml, crates/contracts/hydentity/Cargo.toml, crates/contracts/hyllar/Cargo.toml, crates/contracts/risc0-recursion/Cargo.toml, crates/contracts/staking/Cargo.toml, crates/contracts/uuid-tld/Cargo.toml, crates/hyle-verifiers/Cargo.toml
This reverts commit 4822dc985c0a6aa29a3f1a7a1ec63e29a3732ef4.
=> ⬇️  Revert bump risc0-zkvm from 1.2.4 to 1.3.0

.github/workflows/ci.yml, .github/workflows/clippy.yml, Cargo.lock, Cargo.toml, src/bin/hyle.rs, src/consensus.rs, src/genesis.rs, src/mempool.rs, src/mempool/storage.rs, src/single_node_consensus.rs, src/tests/autobahn_testing.rs, src/utils/crypto.rs, src/utils/integration_test.rs, tests/fixtures/test_helpers.rs
The private key is randomly generated & stored given the validator name
We can set the private key using an hex string in an env var (meant for
kubernetes setup using kube secrets)
In testing env, the private keys are deterministically generated from
the validator name, to keep same behavior as before.
=> 🔒️ Use keyring to store random private key

crates/hyle-model/src/node/consensus.rs, src/consensus.rs, src/consensus/role_follower.rs, src/consensus/role_leader.rs, src/consensus/role_sync.rs, src/consensus/role_timeout.rs, src/genesis.rs, src/mempool.rs, src/mempool/block_construction.rs, src/single_node_consensus.rs, src/tests/autobahn_testing.rs
- Move slot/view to the bft_round_state object to reflect that this is 'trusted state'
- Making consensus_proposal the `current_proposal` we are examining, which can be replaced without breaking assumptions, clarifying the code in finish_round a bit
- Remove round_leader because we need two round robins - one for views, one for slots.
=> ♻️ Refactor view/CP in consensus

src/mempool.rs, src/mempool/block_construction.rs, src/mempool/own_lane.rs, src/mempool/storage.rs, src/mempool/storage_fjall.rs, src/mempool/storage_memory.rs, src/tests/autobahn_testing.rs
- Makes it faster to update signatures since we don't need to compress/decompress so much data
- Makes it workable to quickly get pending DPs and still only process one
=> ⚡️ Split DP & metadata (signatures, ...) in mempool storage.

crates/hyle-model/src/node/consensus.rs, src/consensus.rs, src/consensus/role_leader.rs
We wait `slot_duration` only if:
- it's a new slot
- mempool answered in time
- the cut is different from the last
=> ✨ Start new consensus slots faster unless we are making no progress

src/data_availability.rs, src/indexer.rs, src/indexer/contract_state_indexer.rs, src/indexer/da_listener.rs, src/node_state.rs, src/node_state/module.rs, src/node_state/test/contract_registration_tests.rs, src/node_state/test/node_state_tests.rs
This used to error out, but it should probably kill the node instead.
=> 🔒 Fail to process wrong blocks in node_state

src/mempool.rs, src/mempool/own_lane.rs, src/utils/mod.rs, src/utils/ordered_join_set.rs
On DP creation, we always disseminate it. Because we send in order, they will be processed in order so in general things work perfectly. This means we can bump the retry timer to a much higher value, only for use in case of serious issues.
=> ⚡️ Optimise DP dissemination

crates/hyle-net/src/tcp/p2p_server.rs, src/mempool/verify_tx.rs
This avoids a situation where we receive several DPS, and by the time the hashing of the second is done we haven't done processing the first. We'd buffer it and just forget about it.
=> ⚡️ Process buffered DP when done with one
